debug: false
management.endpoints.web.exposure.include: "*"  # spring actuator

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bootex
    username: bootuser
    password: bootuser
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    #open-in-view: false
    show-sql: true
    # 내가 사용하는 구현체 전용으로 사용하고싶은 properties를 사용하고 싶을 때 사용.
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      database-platform: org.hibernate.dialect.MySQLDialect
  h2.console.enabled: false
#  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated

---
# yaml 파일은 --- 를 기준으로 새로운 document를 생성할 수 있다.
#
spring:
  config.activate.on-profile: testdb
  datasource:
    url: jdbc:h2:mem:board;mode=MariaDB
    driverClassName: org.h2.Driver
#  sql.init.mode: always
  test.database.replace: none
